### ISSUE TITLE
How to remove default padding, or maybe set custom padding

### ISSUE THREAD

**Issue by lordfarhan** [mars885/persistentsearchview#11]

**Comment by mars885** [comment]
Hello.

You can specify the padding [as shown here](https://github.com/mars885/persistentsearchview/blob/master/sample/src/main/res/layout/demo_activity_layout.xml#L73).

Hope that helps.

**Comment by lordfarhan** [comment]
Thanks sir for the response, I have removed all the padding attribute, but it still shown space outside the search view.

**Comment by mars885** [comment]
That is probably due to CardView's compat padding. I will add PersistenSearchView.disableCardViewPadding() method in the upcoming release. Stay tuned for that.

**Comment by lordfarhan** [comment]
I will wait the upcoming release sir thanks a lot 👍
