### ISSUE TITLE
Strange background image

### ISSUE THREAD

**Issue by mercuriy94** [mars885/persistentsearchview#13]
Hello!
Thank you for the wonderful library!
When I use `app:shouldDimBehind = "true"`, I get a strange image in center.
The same is observed in your example.
Thanks!

![strange_image](https://user-images.githubusercontent.com/15321174/76098662-0fcd6780-5ff4-11ea-81ff-06e3e65188c4.png)

**Comment by mars885** [comment]
Hey there.

`app:shouldDimBehind = "true"` dims the background of your screen when the search view becomes focused. It is not actually the image. As far as I remember, it just changes the alpha of the background to give it a dimmed look.

It you want to remove it, just set it `false` and problem solved.

Hope it helps.

**Comment by mercuriy94** [comment]
Hello!
Yes, but then there will be no background dimming effect.
I think the persistentsearchview changes its height and there are internal view elements with alpha and when two or more elements are applied, a darker shade appears.

**Comment by mars885** [comment]
I'm not sure I'm following you. 

What exactly do want to do? Disable the dimming?

**Comment by mars885** [comment]
Have you resolved the issue since quote a lot of time has passed since your last response?
